apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: canary-helloworld
  namespace: default
spec:
  destination:
    name: helloworld-service
  match:
    httpHeaders:
      Foo:
        exact: bar
  route:
  - labels:
      version: v1
    weight: 100
