apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: helloworld-default
  namespace: default
spec:
  destination:
    name: helloworld-service
  precedence: 1
  route:
  - labels:
      version: v1
