apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: helloworld-service-503
  namespace: default
spec:
  destination:
    name: helloworld-service
  precedence: 10
  route:
  - labels:
      version: "2.0"
  httpFault:
    abort:
      percent: 100
      httpStatus: 503
