apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: helloworld-service-chrome
  namespace: default
spec:
  destination:
    name: helloworld-service
  precedence: 3
  match:
    request:
      headers:
        user-agent:
          regex: ".*Chrome.*"
  route:
  - labels:
      version: "2.0"
