apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: canary-helloworld
  namespace: default
spec:
  destination:
    name: helloworld-service
  match:
    request:
      headers:
        user-agent:
          exact: mobile
  precedence: 2
  route:
    - labels:
        version: "2.0"
