apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: guestbook-test-delay
  namespace: default
spec:
  destination:
    name: helloworld-service
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          exact: mobile
  route:
  - labels:
      version: v2
  httpFault:
    delay:
      percent: 100
      fixedDelay: 10s
