apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: guestbook-ui-chrome
spec:
  destination:
    name: guestbook-ui
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Chrome.*"
  route:
  - labels:
      version: "2.0"
